language: scala
jdk: oraclejdk8
scala: 2.12.6
script: sbt ";^^$TRAVIS_SBT_VERSION;verify"

matrix:
  include:
  - env: TRAVIS_SBT_VERSION="0.13.17"
  - env: TRAVIS_SBT_VERSION="1.0.4"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never
